//
//  recallList.swift
//  ProductRecallTests
//
//  Created by fred on 22/04/2022.
//
@testable import ProductRecall

var listMock = Product(count: 10, records: [
    Record(isPersistent: false,
           cardRef: Optional("2022-04-0179"),
           legalCharacter: Optional("Volontaire (sans arrêté préfectoral)"),
           category: Optional("Alimentation"),
           subCategory: Optional("Lait et produits laitiers"),
           brandName: Optional("Les chèvres d\'Amandine"),
           modelName: Optional("Cabécou, gramat, montdoux, faisselle, fromages frais"),
           productId: Optional("06/04/2022, 07/04/2022 et 21/04/2022 Date limite de consommation 07/05/2022"),
           packaging: nil,
           marketingDates: Optional("Du 08/04/2022 au 18/04/2022"),
           storageTemperature: Optional("Produit à conserver au réfrigérateur"),
           healthMark: Optional("82132001"), infos: nil,
           saleGeoArea: Optional("France entière"),
           distributor: Optional("Sarl aux bons fromages, chez le producteur, boucherie pinto, promocash Montauban."),
           reasonRecall: Optional("LISTERIA"),
           risksIncurred: Optional("Listeria monocytogenes (agent responsable de la listériose)"),
           healthRecommendations: Optional("consulter leur médecin traitant en lui signalant cette consommation."),
           additionalRiskDescription: nil,
           actionsToTake: Optional("Ne plus consommer"),
           contactNumber: nil,
           compensationTerms: Optional("Echange"),
           endDateRecall: nil, otherInfos: nil,
           imagesLink: Optional("http://rappel.conso.gouv.fr/image/a72bd35b-640d-4a6e-9011-bdee0529fda0.jpg"),
           flyerLink: Optional("http://rappel.conso.gouv.fr/affichettePDF/6903/Interne"),
           dateRef: Optional("2022-04")),
    Record(isPersistent: false,
           cardRef: Optional("2022-04-0177"),
           legalCharacter: Optional("Volontaire (sans arrêté préfectoral)"),
           category: Optional("Alimentation"),
           subCategory: Optional("Noix et graines"),
           brandName: Optional("B&S CUISINE"),
           modelName: Optional("PISTACHE DECORTIQUEE sachet 250g B&S CUISINE"),
           productId: Optional("3580281252024 1006 Date limite de consommation 30/04/2023"),
           packaging: Optional("PAQUET 250g"),
           marketingDates: Optional("Du 09/03/2022 au 08/04/2022"),
           storageTemperature: Optional("Produit à conserver à température ambiante"),
           healthMark: nil,
           infos: nil,
           saleGeoArea: Optional("France entière"),
           distributor: Optional("magasins GRAND FRAIS"),
           reasonRecall: Optional("Présence de pesticides en quantité supérieure à la LMR de l\'UE"),
           risksIncurred: Optional("Dépassement des limites autorisées de pesticides"),
           healthRecommendations: nil,
           additionalRiskDescription: Optional("Présence de pesticides en quantité supérieure à la LMR de l\'UE"),
           actionsToTake: Optional("Ne plus consommer"),
           contactNumber: nil,
           compensationTerms: Optional("Remboursement Echange"),
           endDateRecall: Optional("samedi 21 mai 2022"),
           otherInfos: nil,
           imagesLink: Optional("http://rappel.conso.gouv.fr/image/de17a324-1f73-4809-9936-9620f42c9765.jpg"),
           flyerLink: Optional("http://rappel.conso.gouv.fr/affichettePDF/6901/Interne"),
           dateRef: Optional("2022-04")),
    Record(isPersistent: false,
           cardRef: Optional("2022-04-0172"),
           legalCharacter: Optional("Volontaire (sans arrêté préfectoral)"),
           category: Optional("Alimentation"),
           subCategory: Optional("Plats préparés et snacks"),
           brandName: Optional("PAS DE MARQUE : FABRICATION MAISON"),
           modelName: Optional("coquille saint jacques vendue au rayon trad traiteur en libre service"),
           productId: Optional("0206302000000   0208009000000 094 Date limite de consommation 16/04/2022"),
           packaging: Optional("vendue à l\'unité au rayon traiteur traditionnel libre service."),
           marketingDates: Optional("Du 05/04/2022 au 13/04/2022"),
           storageTemperature: Optional("Produit à conserver au réfrigérateur"),
           healthMark: nil,
           infos: nil,
           saleGeoArea: Optional("VENDU AU CENTRE E.LECLERC de LAMBALLE."),
           distributor: Optional("E.LECLERC DE LAMBALLE 66 rue mouexigné 22400 LAMBALLE"),
           reasonRecall: Optional("PRESENCE DE LISTERIA MONOCYTOGENES"),
           risksIncurred: Optional("Listeria monocytogenes (agent responsable de la listériose)"),
           healthRecommendations: Optional("consulter leur médecin traitant."),
           additionalRiskDescription: nil,
           actionsToTake: Optional("Ne plus consommer Rapporter le produit au point de vente"),
           contactNumber: Optional("0296501130"),
           compensationTerms: Optional("Remboursement"),
           endDateRecall: Optional("lundi 20 juin 2022"),
           otherInfos: Optional("Pour tout renseignements complémentaire, veuillez contacter le 02.96.50.11.30"),
           imagesLink: Optional("http://rappel.conso.gouv.fr/image/6d92e2f2-3d62-4b05-b084-5ab692824d8e.jpg"),
           flyerLink: Optional("http://rappel.conso.gouv.fr/affichettePDF/6896/Interne"),
           dateRef: Optional("2022-04")),
    Record(isPersistent: false,
           cardRef: Optional("2022-04-0171"),
           legalCharacter: Optional("Imposé par arrêté préfectoral"),
           category: Optional("Alimentation"),
           subCategory: Optional("Viandes"),
           brandName: Optional("SALAISONS DE LA VERNEDE"),
           modelName: Optional("PATE FOUR"),
           productId: Optional("LOT 11 LOT 14"),
           packaging: Optional("SOUS VIDE"),
           marketingDates: Optional("Du 15/03/2022 au 20/04/2022"),
           storageTemperature: Optional("Produit à conserver au réfrigérateur"),
           healthMark: Optional("FR81124027CE"),
           infos: nil,
           saleGeoArea: Optional("France entière"),
           distributor: Optional("RAYGAL LACAUNE\r\nMAISON MIMOSA PORTIRAGNES"),
           reasonRecall: Optional("SUSPICION DE LISTERIA MONOCYTOGENES"),
           risksIncurred: Optional("Listeria monocytogenes (agent responsable de la listériose)"),
           healthRecommendations: Optional("consulter leur médecin traitant."),
           additionalRiskDescription: nil,
           actionsToTake: Optional("Ne plus consommer Rapporter le produit au point de vente"),
           contactNumber: Optional("0563370426"),
           compensationTerms: Optional("Remboursement"),
           endDateRecall: Optional("mardi 10 mai 2022"),
           otherInfos: Optional("ENSEMBLE DE LOTS CONCERNÉES"),
           imagesLink: Optional("http://rappel.conso.gouv.fr/image/44762f90-ff54-4e2e-966d-1a3bfed323fc.jpg"),
           flyerLink: Optional("http://rappel.conso.gouv.fr/affichettePDF/6895/Interne"),
           dateRef: Optional("2022-04")),
    Record(isPersistent: false,
           cardRef: Optional("2022-04-0170"),
           legalCharacter: Optional("Imposé par arrêté préfectoral"),
           category: Optional("Alimentation"),
           subCategory: Optional("Viandes"),
           brandName: Optional("SALAISONS DE LA VERNEDE"),
           modelName: Optional("MELSATS"),
           productId: Optional("LOT 10 LOT 14"),
           packaging: Optional("SOUS VIDE"),
           marketingDates: Optional("Du 08/03/2022 au 20/04/2022"),
           storageTemperature: Optional("Produit à conserver au réfrigérateur"),
           healthMark: Optional("FR81124027CE"),
           infos: nil,
           saleGeoArea: Optional("France entière"),
           distributor: Optional("MAISON HERVE TOULOUSE\r\nSARL SOVIT ALBI\r\nnWEYDMANN RIOLS"),
           reasonRecall: Optional("SUSPICION DE LISTERIA"),
           risksIncurred: Optional("consulter leur médecin traitant"),
           healthRecommendations: "",
           additionalRiskDescription: nil,
           actionsToTake: Optional("Ne plus consommer Rapporter le produit au point de vente"),
           contactNumber: Optional("0563370426"),
           compensationTerms: Optional("Remboursement"),
           endDateRecall: Optional("dimanche 8 mai 2022"),
           otherInfos: Optional("ENSEMBLE DE LOTS CONCERNEES"),
           imagesLink: Optional("http://rappel.conso.gouv.fr/image/54da0e0b-1fe4-4533-8de8-bfe509518d88.jpg"),
           flyerLink: Optional("http://rappel.conso.gouv.fr/affichettePDF/6894/Interne"),
           dateRef: Optional("2022-04")),
    Record(isPersistent: false,
           cardRef: Optional("2022-04-0169"),
           legalCharacter: Optional("Volontaire (sans arrêté préfectoral)"),
           category: Optional("Alimentation"),
           subCategory: Optional("Viandes"),
           brandName: Optional("SALAISONS DE LA VERNEDE"),
           modelName: Optional("TRIPES"),
           productId: Optional("LOT 11/ LOT 12// LOT 14"),
           packaging: Optional("SOUS VIDE"),
           marketingDates: Optional("Du 15/03/2022 au 20/04/2022"),
           storageTemperature: Optional("Produit à conserver au réfrigérateur"),
           healthMark: Optional("81124027CE"),
           infos: nil, saleGeoArea: Optional("France entière"),
           distributor: Optional("SARL CALAS LACAUNE\r\nMAISON ENJALBAL LACAUNE"),
           reasonRecall: Optional("LISTERIA MONOCYTOGENES"),
           risksIncurred: Optional("consulter leur médecin traitant."),
           healthRecommendations: "",
           additionalRiskDescription: nil,
           actionsToTake: Optional("Ne plus consommer Rapporter le produit au point de vente Détruire le produit"),
           contactNumber: Optional("0563370426"),
           compensationTerms: Optional("Remboursement"),
           endDateRecall: Optional("dimanche 1 mai 2022"),
           otherInfos: Optional("ENSEMBLE DE LOTS CONCERNEES"),
           imagesLink: Optional("http://rappel.conso.gouv.fr/image/5b006b32-a53b-49e2-a6d2-56d38f827ba8.jpg"),
           flyerLink: Optional("http://rappel.conso.gouv.fr/affichettePDF/6893/Interne"),
           dateRef: Optional("2022-04")),
    Record(isPersistent: false,
           cardRef: Optional("2022-04-0168"),
           legalCharacter: Optional("Volontaire (sans arrêté préfectoral)"),
           category: Optional("Alimentation"),
           subCategory: Optional("Viandes"),
           brandName: Optional("Sans marque"),
           modelName: Optional("Merguez à griller vrac"),
           productId: Optional("0212601000000 Lot Fabrication 2022-109"),
           packaging: Optional("Vrac"),
           marketingDates: Optional("Du 19/04/2022 au 19/04/2022"),
           storageTemperature: Optional("Produit à conserver au réfrigérateur"),
           healthMark: nil,
           infos: nil,
           saleGeoArea: Optional("E.Leclerc Creutzwald"),
           distributor: Optional("E.Leclerc Creutzwald"),
           reasonRecall: Optional("Suspicion présence de corps étranger"),
           risksIncurred: Optional("Inertes (verre, métal, plastique, papier, textile…)"),
           healthRecommendations: Optional("Ne pas consommer."),
           additionalRiskDescription: nil,
           actionsToTake: Optional("Ne plus consommer Contacter le point de vente Contacter le service consommateur"),
           contactNumber: Optional("0387292333"),
           compensationTerms: Optional("Remboursement"),
           endDateRecall: Optional("lundi 2 mai 2022"),
           otherInfos: nil,
           imagesLink: Optional("http://rappel.conso.gouv.fr/image/d79381bb-b77c-4369-a2d4-8f0c13fb0f13.jpg"),
           flyerLink: Optional("http://rappel.conso.gouv.fr/affichettePDF/6892/Interne"),
           dateRef: Optional("2022-04")),
    Record(isPersistent: false,
           cardRef: Optional("2022-04-0167"),
           legalCharacter: Optional("Volontaire (sans arrêté préfectoral)"),
           category: Optional("Alimentation"),
           subCategory: Optional("Produits de la pêche et d\'aquaculture"),
           brandName: Optional("SANS MARQUE"),
           modelName: Optional("Blanquette de Cabillaud 800g"),
           productId: Optional("Date limite de consommation 17/04/2022"),
           packaging: Optional("barquette plastique de 800g"),
           marketingDates: Optional("Du 14/04/2022 au 17/04/2022"),
           storageTemperature: Optional("Produit à conserver au réfrigérateur"),
           healthMark: nil,
           infos: nil,
           saleGeoArea: Optional("Régions: Hauts-de-France"),
           distributor: Optional("supermarché Match Villeneuve d\'Ascq Haute Borne"),
           reasonRecall: Optional("Présence éventuelle de corps étrangers"),
           risksIncurred: Optional("Inertes (verre, métal, plastique, papier, textile…)"),
           healthRecommendations: Optional("Ne pas consommer."),
           additionalRiskDescription: Optional("Morceaux de plastique"),
           actionsToTake: Optional("Ne plus consommer Rapporter le produit au point de vente"),
           contactNumber: Optional("0374954440"),
           compensationTerms: Optional("Remboursement"),
           endDateRecall: Optional("mercredi 4 mai 2022"),
           otherInfos: nil,
           imagesLink: Optional("http://rappel.conso.gouv.fr/image/5e71a429-c01b-4193-b001-c526ebcad0f6.jpg"),
           flyerLink: Optional("http://rappel.conso.gouv.fr/affichettePDF/6891/Interne"),
           dateRef: Optional("2022-04")),
    Record(isPersistent: false,
           cardRef: Optional("2022-04-0163"),
           legalCharacter: Optional("Imposé par arrêté préfectoral"),
           category: Optional("Alimentation"),
           subCategory: Optional("Viandes"),
           brandName: Optional("SALAISONS DE LA VERNEDE"),
           modelName: Optional("BOUDINS LANGUES\r\nBOUDINS OIGNONS\r\nBOUDINS BRASSES\r\nBOUDINS"),
           productId: Optional("10-12-14"),
           packaging: Optional("SOUS VIDE"),
           marketingDates: Optional("Du 10/03/2022 au 15/04/2022"),
           storageTemperature: Optional("Produit à conserver au réfrigérateur"),
           healthMark: Optional("FR81124027CE"),
           infos: Optional("FR81124027 CE\r\nSALAISONS DE LA VERNEDE"),
           saleGeoArea: Optional("France entière"),
           distributor: Optional("VOIR INFORMATIONS COMPLEMENTAIRES"),
           reasonRecall: Optional("LISTERIA MONOCYTOGENES"),
           risksIncurred: Optional("Listeria monocytogenes (agent responsable de la listériose) Intoxication"),
           healthRecommendations: Optional("consulter leur médecin traitant."),
           additionalRiskDescription: nil,
           actionsToTake: Optional("Ne plus consommer Rapporter le produit au point de vente"),
           contactNumber: Optional("0563370426"),
           compensationTerms: Optional("Remboursement"),
           endDateRecall: Optional("dimanche 8 mai 2022"),
           otherInfos: Optional("EUROCHARCUTERIE TOULOUSE\r\nLE RAYGAL LACAUNE"),
           imagesLink: Optional("http://rappel.conso.gouv.fr/image/2e16db4f-beb0-49a5-b4ed-44ee137b3d4f.jpg"),
           flyerLink: Optional("http://rappel.conso.gouv.fr/affichettePDF/6887/Interne"),
           dateRef: Optional("2022-04")),
    Record(isPersistent: false,
           cardRef: Optional("2022-04-0162"),
           legalCharacter: Optional("Volontaire (sans arrêté préfectoral)"),
           category: Optional("Alimentation"),
           subCategory: Optional("Plats préparés et snacks"),
           brandName: Optional("LA PIZZA DE MANOSQUE"),
           modelName: Optional("Mini Pizza Jambon fromage"),
           productId: Optional("3424600001354 017/22 et 018/22 "),
           packaging: Optional("Barquette de couleur blanche + film transparent"),
           marketingDates: Optional("Du 29/07/2021 au 04/04/2022"),
           storageTemperature: Optional("Produit à conserver au congélateur"),
           healthMark: nil, infos: Optional("9 mini pizzas au jambon fromage emballées dans une barquette blanche."),
           saleGeoArea: Optional("France entière"),
           distributor: Optional("Les points de ventes ECOMIAM"),
           reasonRecall: Optional("Il manque des informations sur la liste d\'ingrédients."),
           risksIncurred: Optional("Substances allergisantes non déclarées"),
           healthRecommendations: nil,
           additionalRiskDescription: nil,
           actionsToTake: Optional("Rapporter le produit au point de vente"),
           contactNumber: Optional("0492705790"),
           compensationTerms: Optional("Autre (voir informations complémentaires)"),
           endDateRecall: Optional("jeudi 30 juin 2022"),
           otherInfos: Optional("Avoir au consommateur qui rapportera le produit concerné par le rappel."),
           imagesLink: Optional("http://rappel.conso.gouv.fr/image/6401d914-2843-4460-b222-96d7404a3dd3.jpg"),
           flyerLink: Optional("http://rappel.conso.gouv.fr/affichettePDF/6886/Interne"),
           dateRef: Optional("2022-04"))
])
